### ISSUE TITLE
Fix LICENSE.md and license description in files

### ISSUE THREAD

**Issue by KristofferC** [chakravala/VerTeX.jl#1]
The LICENSE in this packge and the snippet in the repl.jl file says

```
#   This file is part of VerTeX.jl. It is licensed under the MIT license
#   Copyright (C) 2019 Michael Reed
```

A lot of the repl.jl file is copy pasted from Pkg which is under the MIT license which states:

```
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
```

so the code here right now is in violation of the license. It would be good to update the license to say that the REPL.jl code was derived from Pkg and add the text from Pkg.jl's LICENSE.md.

**Comment by KristofferC** [comment]
Also, just to point out, this package seems to fail on Julia master, probably due to some changes in Pkg internals.

**Comment by chakravala** [comment]
Thanks for notifying, I will address this when I get around to it in a few days.

**Comment by chakravala** [comment]
Issue is now resolved, let me know if the LICENSE attribution is satisfactory or not.
